-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity contrastadj_AXIvideo2xfMat_24_9_1080_1920_1_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    img1_431_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    img1_431_full_n : IN STD_LOGIC;
    img1_431_write : OUT STD_LOGIC;
    src_axi_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    src_axi_TVALID : IN STD_LOGIC;
    src_axi_TREADY : OUT STD_LOGIC;
    src_axi_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    src_axi_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    src_axi_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_axi_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_axi_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_axi_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    adj : IN STD_LOGIC_VECTOR (31 downto 0);
    adj_ap_vld : IN STD_LOGIC;
    adj_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    adj_out_full_n : IN STD_LOGIC;
    adj_out_write : OUT STD_LOGIC );
end;


architecture behav of contrastadj_AXIvideo2xfMat_24_9_1080_1920_1_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv11_438 : STD_LOGIC_VECTOR (10 downto 0) := "10000111000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_780 : STD_LOGIC_VECTOR (10 downto 0) := "11110000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal img1_431_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln132_reg_352 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_axi_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal icmp_ln132_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln138_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_phi_mux_last_1_phi_fu_279_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal adj_blk_n : STD_LOGIC;
    signal adj_out_blk_n : STD_LOGIC;
    signal axi_last_V_1_reg_170 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_1_reg_181 : STD_LOGIC_VECTOR (23 downto 0);
    signal j_reg_192 : STD_LOGIC_VECTOR (10 downto 0);
    signal last_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal start_1_reg_215 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_3_reg_226 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_reg_239 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_data_V_reg_330 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_last_V_reg_338 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln128_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_3_fu_306_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_347 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_predicate_op115_read_state5 : BOOLEAN;
    signal ap_block_state5_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal j_2_fu_318_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state8 : BOOLEAN;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state5 : STD_LOGIC;
    signal axi_last_V_3_reg_252 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_0_reg_125 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal axi_data_V_3_reg_264 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_data_V_0_reg_135 : STD_LOGIC_VECTOR (23 downto 0);
    signal i_reg_145 : STD_LOGIC_VECTOR (10 downto 0);
    signal start_reg_156 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_axi_last_V_1_phi_fu_173_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_axi_data_V_1_phi_fu_184_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_mux_last_phi_fu_207_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_start_1_phi_fu_218_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp1_iter0_last_3_reg_226 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp1_iter0_p_Val2_s_reg_239 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal last_1_reg_276 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal axi_user_V_fu_296_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_data_V_U_apdone_blk : STD_LOGIC;
    signal src_axi_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal src_axi_TVALID_int_regslice : STD_LOGIC;
    signal src_axi_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal src_axi_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_AXI_video_strm_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal src_axi_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_AXI_video_strm_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_apdone_blk : STD_LOGIC;
    signal src_axi_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_apdone_blk : STD_LOGIC;
    signal src_axi_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_apdone_blk : STD_LOGIC;
    signal src_axi_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal src_axi_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_condition_159 : BOOLEAN;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_AXI_video_strm_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_axi_TDATA,
        vld_in => src_axi_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_data_V_U_ack_in,
        data_out => src_axi_TDATA_int_regslice,
        vld_out => src_axi_TVALID_int_regslice,
        ack_out => src_axi_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_data_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_axi_TKEEP,
        vld_in => src_axi_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_keep_V_U_ack_in,
        data_out => src_axi_TKEEP_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_keep_V_U_vld_out,
        ack_out => src_axi_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_axi_TSTRB,
        vld_in => src_axi_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_strb_V_U_ack_in,
        data_out => src_axi_TSTRB_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_strb_V_U_vld_out,
        ack_out => src_axi_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_axi_TUSER,
        vld_in => src_axi_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_user_V_U_ack_in,
        data_out => src_axi_TUSER_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_user_V_U_vld_out,
        ack_out => src_axi_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_user_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_axi_TLAST,
        vld_in => src_axi_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_last_V_U_ack_in,
        data_out => src_axi_TLAST_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_last_V_U_vld_out,
        ack_out => src_axi_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_last_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_axi_TID,
        vld_in => src_axi_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_id_V_U_ack_in,
        data_out => src_axi_TID_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_id_V_U_vld_out,
        ack_out => src_axi_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_id_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_axi_TDEST,
        vld_in => src_axi_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_dest_V_U_ack_in,
        data_out => src_axi_TDEST_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_dest_V_U_vld_out,
        ack_out => src_axi_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state5);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_V_0_reg_135_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                axi_data_V_0_reg_135 <= axi_data_V_reg_330;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                axi_data_V_0_reg_135 <= axi_data_V_3_reg_264;
            end if; 
        end if;
    end process;

    axi_data_V_1_reg_181_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                axi_data_V_1_reg_181 <= p_Val2_s_reg_239;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_0))) then 
                axi_data_V_1_reg_181 <= axi_data_V_0_reg_135;
            end if; 
        end if;
    end process;

    axi_data_V_3_reg_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                axi_data_V_3_reg_264 <= axi_data_V_1_reg_181;
            elsif ((not(((src_axi_TVALID_int_regslice = ap_const_logic_0) and (last_1_reg_276 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (last_1_reg_276 = ap_const_lv1_0))) then 
                axi_data_V_3_reg_264 <= src_axi_TDATA_int_regslice;
            end if; 
        end if;
    end process;

    axi_last_V_0_reg_125_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                axi_last_V_0_reg_125 <= axi_last_V_reg_338;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                axi_last_V_0_reg_125 <= axi_last_V_3_reg_252;
            end if; 
        end if;
    end process;

    axi_last_V_1_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                axi_last_V_1_reg_170 <= last_3_reg_226;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_0))) then 
                axi_last_V_1_reg_170 <= axi_last_V_0_reg_125;
            end if; 
        end if;
    end process;

    axi_last_V_3_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                axi_last_V_3_reg_252 <= axi_last_V_1_reg_170;
            elsif ((not(((src_axi_TVALID_int_regslice = ap_const_logic_0) and (last_1_reg_276 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (last_1_reg_276 = ap_const_lv1_0))) then 
                axi_last_V_3_reg_252 <= src_axi_TLAST_int_regslice;
            end if; 
        end if;
    end process;

    i_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_reg_145 <= ap_const_lv11_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                i_reg_145 <= i_3_reg_347;
            end if; 
        end if;
    end process;

    j_reg_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_fu_312_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                j_reg_192 <= j_2_fu_318_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_0))) then 
                j_reg_192 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    last_1_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                last_1_reg_276 <= last_reg_203;
            elsif ((not(((src_axi_TVALID_int_regslice = ap_const_logic_0) and (last_1_reg_276 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (last_1_reg_276 = ap_const_lv1_0))) then 
                last_1_reg_276 <= src_axi_TLAST_int_regslice;
            end if; 
        end if;
    end process;

    last_3_reg_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_159)) then
                if (((or_ln138_fu_324_p2 = ap_const_lv1_0) and (icmp_ln132_fu_312_p2 = ap_const_lv1_0))) then 
                    last_3_reg_226 <= src_axi_TLAST_int_regslice;
                elsif (((or_ln138_fu_324_p2 = ap_const_lv1_1) and (icmp_ln132_fu_312_p2 = ap_const_lv1_0))) then 
                    last_3_reg_226 <= ap_phi_mux_axi_last_V_1_phi_fu_173_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    last_3_reg_226 <= ap_phi_reg_pp1_iter0_last_3_reg_226;
                end if;
            end if; 
        end if;
    end process;

    last_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                last_reg_203 <= last_3_reg_226;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_0))) then 
                last_reg_203 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    p_Val2_s_reg_239_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_159)) then
                if (((or_ln138_fu_324_p2 = ap_const_lv1_0) and (icmp_ln132_fu_312_p2 = ap_const_lv1_0))) then 
                    p_Val2_s_reg_239 <= src_axi_TDATA_int_regslice;
                elsif (((or_ln138_fu_324_p2 = ap_const_lv1_1) and (icmp_ln132_fu_312_p2 = ap_const_lv1_0))) then 
                    p_Val2_s_reg_239 <= ap_phi_mux_axi_data_V_1_phi_fu_184_p4;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_Val2_s_reg_239 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_239;
                end if;
            end if; 
        end if;
    end process;

    start_1_reg_215_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                start_1_reg_215 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_0))) then 
                start_1_reg_215 <= start_reg_156;
            end if; 
        end if;
    end process;

    start_reg_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                start_reg_156 <= ap_const_lv1_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                start_reg_156 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((src_axi_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                axi_data_V_reg_330 <= src_axi_TDATA_int_regslice;
                axi_last_V_reg_338 <= src_axi_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_3_reg_347 <= i_3_fu_306_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln132_reg_352 <= icmp_ln132_fu_312_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, adj_ap_vld, adj_out_full_n, ap_CS_fsm_state2, ap_enable_reg_pp1_iter0, icmp_ln132_fu_312_p2, ap_CS_fsm_state8, ap_phi_mux_last_1_phi_fu_279_p4, icmp_ln128_fu_300_p2, ap_CS_fsm_state4, ap_block_pp1_stage0_subdone, last_1_reg_276, axi_user_V_fu_296_p1, src_axi_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_const_logic_0 = adj_out_full_n) or (ap_const_logic_0 = adj_ap_vld) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((src_axi_TVALID_int_regslice = ap_const_logic_1) and (axi_user_V_fu_296_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((src_axi_TVALID_int_regslice = ap_const_logic_1) and (axi_user_V_fu_296_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((icmp_ln132_fu_312_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((icmp_ln132_fu_312_p2 = ap_const_lv1_1) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if ((not(((src_axi_TVALID_int_regslice = ap_const_logic_0) and (last_1_reg_276 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (last_1_reg_276 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif ((not(((src_axi_TVALID_int_regslice = ap_const_logic_0) and (last_1_reg_276 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (ap_phi_mux_last_1_phi_fu_279_p4 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;

    adj_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, adj_ap_vld)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            adj_blk_n <= adj_ap_vld;
        else 
            adj_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    adj_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, adj_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            adj_out_blk_n <= adj_out_full_n;
        else 
            adj_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    adj_out_din <= adj;

    adj_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, adj_ap_vld, adj_out_full_n)
    begin
        if ((not(((ap_const_logic_0 = adj_out_full_n) or (ap_const_logic_0 = adj_ap_vld) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            adj_out_write <= ap_const_logic_1;
        else 
            adj_out_write <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state7 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(6);
    ap_CS_fsm_state9 <= ap_CS_fsm(7);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(img1_431_full_n, ap_enable_reg_pp1_iter1, icmp_ln132_reg_352, ap_enable_reg_pp1_iter0, ap_predicate_op115_read_state5, src_axi_TVALID_int_regslice)
    begin
                ap_block_pp1_stage0_01001 <= (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (src_axi_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or ((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (img1_431_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(img1_431_full_n, ap_enable_reg_pp1_iter1, icmp_ln132_reg_352, ap_enable_reg_pp1_iter0, ap_predicate_op115_read_state5, src_axi_TVALID_int_regslice)
    begin
                ap_block_pp1_stage0_11001 <= (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (src_axi_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or ((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (img1_431_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(img1_431_full_n, ap_enable_reg_pp1_iter1, icmp_ln132_reg_352, ap_enable_reg_pp1_iter0, ap_predicate_op115_read_state5, src_axi_TVALID_int_regslice)
    begin
                ap_block_pp1_stage0_subdone <= (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (src_axi_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or ((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (img1_431_full_n = ap_const_logic_0)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, adj_ap_vld, adj_out_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = adj_out_full_n) or (ap_const_logic_0 = adj_ap_vld) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state5_pp1_stage0_iter0_assign_proc : process(ap_predicate_op115_read_state5, src_axi_TVALID_int_regslice)
    begin
                ap_block_state5_pp1_stage0_iter0 <= ((src_axi_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp1_stage0_iter1_assign_proc : process(img1_431_full_n, icmp_ln132_reg_352)
    begin
                ap_block_state6_pp1_stage0_iter1 <= ((icmp_ln132_reg_352 = ap_const_lv1_0) and (img1_431_full_n = ap_const_logic_0));
    end process;


    ap_block_state8_assign_proc : process(last_1_reg_276, src_axi_TVALID_int_regslice)
    begin
                ap_block_state8 <= ((src_axi_TVALID_int_regslice = ap_const_logic_0) and (last_1_reg_276 = ap_const_lv1_0));
    end process;


    ap_condition_159_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0_11001)
    begin
                ap_condition_159 <= ((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0));
    end process;


    ap_condition_pp1_exit_iter0_state5_assign_proc : process(icmp_ln132_fu_312_p2)
    begin
        if ((icmp_ln132_fu_312_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, icmp_ln128_fu_300_p2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_axi_data_V_1_phi_fu_184_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_352, axi_data_V_1_reg_181, p_Val2_s_reg_239)
    begin
        if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_axi_data_V_1_phi_fu_184_p4 <= p_Val2_s_reg_239;
        else 
            ap_phi_mux_axi_data_V_1_phi_fu_184_p4 <= axi_data_V_1_reg_181;
        end if; 
    end process;


    ap_phi_mux_axi_last_V_1_phi_fu_173_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_352, axi_last_V_1_reg_170, last_3_reg_226)
    begin
        if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_axi_last_V_1_phi_fu_173_p4 <= last_3_reg_226;
        else 
            ap_phi_mux_axi_last_V_1_phi_fu_173_p4 <= axi_last_V_1_reg_170;
        end if; 
    end process;

    ap_phi_mux_last_1_phi_fu_279_p4 <= last_1_reg_276;

    ap_phi_mux_last_phi_fu_207_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_352, last_reg_203, last_3_reg_226)
    begin
        if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_last_phi_fu_207_p4 <= last_3_reg_226;
        else 
            ap_phi_mux_last_phi_fu_207_p4 <= last_reg_203;
        end if; 
    end process;


    ap_phi_mux_start_1_phi_fu_218_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_352, start_1_reg_215)
    begin
        if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_start_1_phi_fu_218_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_start_1_phi_fu_218_p4 <= start_1_reg_215;
        end if; 
    end process;

    ap_phi_reg_pp1_iter0_last_3_reg_226 <= "X";
    ap_phi_reg_pp1_iter0_p_Val2_s_reg_239 <= "XXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op115_read_state5_assign_proc : process(icmp_ln132_fu_312_p2, or_ln138_fu_324_p2)
    begin
                ap_predicate_op115_read_state5 <= ((or_ln138_fu_324_p2 = ap_const_lv1_0) and (icmp_ln132_fu_312_p2 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;
    axi_user_V_fu_296_p1 <= src_axi_TUSER_int_regslice;
    i_3_fu_306_p2 <= std_logic_vector(unsigned(i_reg_145) + unsigned(ap_const_lv11_1));
    icmp_ln128_fu_300_p2 <= "1" when (i_reg_145 = ap_const_lv11_438) else "0";
    icmp_ln132_fu_312_p2 <= "1" when (j_reg_192 = ap_const_lv11_780) else "0";

    img1_431_blk_n_assign_proc : process(img1_431_full_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_352)
    begin
        if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            img1_431_blk_n <= img1_431_full_n;
        else 
            img1_431_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img1_431_din <= p_Val2_s_reg_239;

    img1_431_write_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln132_reg_352, ap_block_pp1_stage0_11001)
    begin
        if (((icmp_ln132_reg_352 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            img1_431_write <= ap_const_logic_1;
        else 
            img1_431_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(icmp_ln128_fu_300_p2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_300_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    j_2_fu_318_p2 <= std_logic_vector(unsigned(j_reg_192) + unsigned(ap_const_lv11_1));
    or_ln138_fu_324_p2 <= (ap_phi_mux_start_1_phi_fu_218_p4 or ap_phi_mux_last_phi_fu_207_p4);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    src_axi_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_CS_fsm_state2, ap_enable_reg_pp1_iter0, icmp_ln132_fu_312_p2, or_ln138_fu_324_p2, ap_CS_fsm_state8, last_1_reg_276, src_axi_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((or_ln138_fu_324_p2 = ap_const_lv1_0) and (icmp_ln132_fu_312_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (last_1_reg_276 = ap_const_lv1_0)))) then 
            src_axi_TDATA_blk_n <= src_axi_TVALID_int_regslice;
        else 
            src_axi_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    src_axi_TREADY <= regslice_both_AXI_video_strm_V_data_V_U_ack_in;

    src_axi_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_CS_fsm_state2, ap_enable_reg_pp1_iter0, ap_CS_fsm_state8, ap_predicate_op115_read_state5, ap_block_pp1_stage0_11001, last_1_reg_276, src_axi_TVALID_int_regslice)
    begin
        if ((((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_predicate_op115_read_state5 = ap_const_boolean_1)) or (not(((src_axi_TVALID_int_regslice = ap_const_logic_0) and (last_1_reg_276 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (last_1_reg_276 = ap_const_lv1_0)) or ((src_axi_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            src_axi_TREADY_int_regslice <= ap_const_logic_1;
        else 
            src_axi_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
